### ISSUE TITLE
Where is the global parameters θ from？

### ISSUE THREAD

**Issue by suanrong** [vkverma01/EFT#1]
Hi, I have a question about the global parameters θ.

In your paper, you mentioned that the global parameters θ remain unchanged. What is the initial value of θ?  Is it from a pretrained model or just learned in the first task? Did I miss something in your paper? 

Thanks~

**Comment by wdmwhh** [comment]
I have read the paper. For the question above, the value is randomly initialized, is trained in the first task, and then remains unchanged in the sequential tasks.
